### ISSUE TITLE
oasfi --version option doesn't work

### ISSUE THREAD

**Issue by hanahiroAze** [oasysgames/oasfi#75]
I'm using oasfi-macos [v0.11.27](https://github.com/oasysgames/oasfi/releases/tag/v0.11.27), and --version option always returns `v1.0.1`.
does this option work correctly?

**Comment by girafferz** [comment]
調査をお願いします！

**Comment by haont0312** [comment]
@girafferz 
この事象の修正が完了致しました！
以下のPRを作成致しましたので、ご確認の上、マージして頂けないでしょうか。
https://github.com/oasysgames/oasfi/pull/77

> 　　・修正前：固定でv1.0.1で設定していた
> 　　・修正後：自動的に最新のTag Versionで設定できる

**Comment by girafferz** [comment]
ありがとうございます！

**Comment by hanahiroAze** [comment]
When I run:

`$ ./oasfi-macos --version`

returnes
` undefined`

is this really fixed?

@girafferz

**Comment by hanahiroAze** [comment]
confirmed fixed in v0.11.30
